dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - elasticsearch
before_script:
  # slow elasticsearch service
  - echo 'waiting for elasticsearch is up'; while ! curl --output /dev/null --silent --head --fail http://localhost:9200; do sleep 1; echo -n '.'; done
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
