dist: trusty
language: python
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-set-default
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.2.2.deb && sudo service elasticsearch start
before_script:
  # slow elasticsearch service
  - echo 'waiting for elasticsearch is up'; while ! curl --output /dev/null --silent --head --fail http://127.0.0.1:9200; do sleep 1; echo -n '.'; done
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
